# Generated by Django 4.0.4 on 2022-11-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
